
- name: Setup Tasks (replaces sccm tasks)
  hosts: all
  gather_facts: false
  tasks:
  
    - name: Remove installed KB2966828
      ignore_errors: yes
      win_hotfix:
        hotfix_kb: KB2966828
        state: absent
      register: hotfix_uninstall

    - name: Remove installed KB2966828
      ignore_errors: yes
      win_hotfix:
        hotfix_kb: KB2966827
        state: absent
      register: hotfix_uninstall

    - name: Remove installed KB2966826
      ignore_errors: yes
      win_hotfix:
        hotfix_kb: KB2966826
        state: absent
      register: hotfix_uninstall

    - name: Install windows DotNet 3.5 FrameWork
      ignore_errors: yes
      win_feature:
        name: Net-Framework-Core
        state: present

    - name: Change the hostname to new_hostname
      win_hostname:
        name: variable ($Desc)

    - name: Query pagefiles configuration
      win_pagefile:

    - name: Query C pagefile
      win_pagefile:
        drive: C

    - name: Set C pagefile, override if exists
      win_pagefile:
        drive: C
        initial_size: 8192
        maximum_size: 8192
        override: no
        state: present

    - name: Set timezone to 'Central Standard Time' (GMT-06:00)
      win_timezone:
        timezone: Central Standard Time

    #- name: Install all security, critical, and rollup updates
    # win_updates:
      #  category_names:
      #   - SecurityUpdates
        #  - CriticalUpdates
        # - UpdateRollups

